<a href="https://colab.research.google.com/github/Praveenraju10/15_days_workshop/blob/main/Day2/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print("all libraries are imported successfully")
print(f"Pandas version is {pd.__version__}")
print(f"SQLite3 version is {sqlite3.version}")

all libraries are imported successfully
Pandas version is 2.2.2
SQLite3 version is 2.6.0

In [18]:
df=pd.read_csv('student_performance.csv')
print(f"Dataset loaded:{df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns:{df.columns.to_list()}")
df.head(3)

Dataset loaded:30 students, 13 columns
Columns:['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023

In [20]:
conn=sqlite3.connect('college.db')
cursor=conn.cursor()
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)

cursor.execute("SELECT COUNT(*) FROM students")

count=cursor.fetchone()[0]
print(f"Number of students in the database:{count}")

Number of students in the database:30

In [23]:
def run_query(sql, description="student"):
  if description:
    print(f"{description}")

  result=pd.read_sql_query(sql, conn)
  return result
print("Helper function 'run_query' defined successfully")
print("Usage: run_quey(sql_string, description_label)")

Helper function 'run_query' defined successfully
Usage: run_quey(sql_string, description_label)

In [29]:
query1="""SELECT student_id from students  Limit 5"""

result1=run_query(query1, "First 10 students")
result1

First 10 students

   student_id
0        1001
1        1002
2        1003
3        1004
4        1005

In [33]:
query2="""select name from students where name between 'A' and 'F'"""

result2=run_query(query2)
result2

student

             name
0    Aarav Sharma
1      Arjun Nair
2     Divya Singh
3      Ananya Das
4     Ajay Tiwari
5  Deepak Chauhan
6       Amit Bose
7  Akanksha Yadav